### PR TITLE
TDL-19447 Update params for content_categories and iab_categories

### PR DESCRIPTION
**Pull request by prijendev**
# Description of change
- Added `count` and `cursor` parameters in the `iab_categories` stream.
-  Removed parameter from the `content_categories` stream.

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

### CODE REVIEW

**Review by dbshah1212 — APPROVED** [review]

**Review by savan-chovatiya — CHANGES_REQUESTED** [review]
Add `IabCategories` stream into the pagination test or remove the workaround for it if present.

**Comment by prijendev** [comment]
> Member



> Add `IabCategories` stream into the pagination test or remove the workaround for it if present.

`IabCategories` stream is already included in the pagination test.

**Review by savan-chovatiya — APPROVED** [review]

**Review by kspeer825 — CHANGES_REQUESTED** [review]
I think this change should have a tap-tester test to cover pagination. I don't think these streams are accounted for on the other branches that have that test.

**Comment by prijendev** [comment]
> I think this change should have a tap-tester test to cover pagination. I don't think these streams are accounted for on the other branches that have that test.

Updated pagination test case to cover `iab_categories` and skipped `content_categories` from test case as it does not support pagination.

**Review by kspeer825 — APPROVED** [review]

**Review by RushiT0122 — APPROVED** [review]

**Review by KrisPersonal — APPROVED** [review]

**Pull request merged**
